### ISSUE TITLE
Execute a Graph

### ISSUE THREAD

**Issue by MMJM** [miroiu/NodeBasedEditor#1]
Hi,

I've been looking at your project and it is very interesting. I've been playing around and I can't seem to get anything to Execute. This is the very simple graph I created.

![image](https://user-images.githubusercontent.com/16725454/43692848-0f2db314-996e-11e8-8487-fa9f85f1e29d.png)

**Comment by miroiu** [comment]
Hello,

Sorry for the late response. For some reason i didn't get notified by email.

The graph editor lets you create a graph but can't execute it. I can tell from the image that you created a Function Graph. 
Every graph comes with an Input and an Output node. Function graphs have those nodes editable, that means you can drag a connection into the node and a new pin will be created.
Now if you want the graph to execute you must provide the necessary data.

Hit the Compile button and it will generate a new entry in the Actions Menu under the Project category.
![image](https://user-images.githubusercontent.com/12727904/43849594-7b63bf66-9b3e-11e8-8a22-21c553201eea.png)

Create a Text Graph or an Image Graph and spawn the new generated node.
![image](https://user-images.githubusercontent.com/12727904/43849784-e7184650-9b3e-11e8-8086-4c9c8bee7043.png)

Open a text/image file and select the text/image graph you want to use then press Run.
![image](https://user-images.githubusercontent.com/12727904/43849990-64dcbe5e-9b3f-11e8-8905-a7fc54a5595e.png)

The input is taken from the text/image file and sent to the Text/Image Graph and the graph is executed.

I know it's a bit too much to execute a simple graph but the intent of the application was to operate on different file types.

[I attached some test graphs](https://www.dropbox.com/s/0m8tyni101y8jtl/Playground.rar?dl=0)

**Comment by miroiu** [comment]
Do you have any additional questions or can i close the issue ?

**Comment by MMJM** [comment]
Thanks. I missed the reply above. Yes I'm all good now.
